// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerAddressResponse) Reset() {
	*x = GetServerAddressResponse{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerAddressResponse) ProtoMessage() {}

func (x *GetServerAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerAddressResponse.ProtoReflect.Descriptor instead.
func (*GetServerAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\x06config\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x18GetServerAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2\xd5\x01\n" +
	"\rConfigService\x12L\n" +
	"\x10GetServerAddress\x12\x16.google.protobuf.Empty\x1a .config.GetServerAddressResponse\x12=\n" +
	"\vLongRunning\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05Flaky\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB;Z9github.com/elisardofelix/grpc-examples/example-6-ha/protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_config_proto_goTypes = []any{
	(*GetServerAddressResponse)(nil), // 0: config.GetServerAddressResponse
	(*emptypb.Empty)(nil),            // 1: google.protobuf.Empty
}
var file_proto_config_proto_depIdxs = []int32{
	1, // 0: config.ConfigService.GetServerAddress:input_type -> google.protobuf.Empty
	1, // 1: config.ConfigService.LongRunning:input_type -> google.protobuf.Empty
	1, // 2: config.ConfigService.Flaky:input_type -> google.protobuf.Empty
	0, // 3: config.ConfigService.GetServerAddress:output_type -> config.GetServerAddressResponse
	1, // 4: config.ConfigService.LongRunning:output_type -> google.protobuf.Empty
	1, // 5: config.ConfigService.Flaky:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
