// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/interceptor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_proto_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_proto_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProtectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectedResponse) Reset() {
	*x = ProtectedResponse{}
	mi := &file_proto_interceptor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedResponse) ProtoMessage() {}

func (x *ProtectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedResponse.ProtoReflect.Descriptor instead.
func (*ProtectedResponse) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{2}
}

func (x *ProtectedResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        map[string]string      `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_interceptor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_proto_interceptor_proto protoreflect.FileDescriptor

const file_proto_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x17proto/interceptor.proto\x12\vinterceptor\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x11ProtectedResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x90\x01\n" +
	"\x10ValidateResponse\x12A\n" +
	"\x06claims\x18\x01 \x03(\v2).interceptor.ValidateResponse.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa4\x02\n" +
	"\x12InterceptorService\x12G\n" +
	"\bSayHello\x12\x1c.interceptor.SayHelloRequest\x1a\x1d.interceptor.SayHelloResponse\x12=\n" +
	"\vLongRunning\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\tProtected\x12\x16.google.protobuf.Empty\x1a\x1e.interceptor.ProtectedResponse\x12A\n" +
	"\bValidate\x12\x16.google.protobuf.Empty\x1a\x1d.interceptor.ValidateResponseB-Z+github.com/cshep4/grpc-course/module5/protob\x06proto3"

var (
	file_proto_interceptor_proto_rawDescOnce sync.Once
	file_proto_interceptor_proto_rawDescData []byte
)

func file_proto_interceptor_proto_rawDescGZIP() []byte {
	file_proto_interceptor_proto_rawDescOnce.Do(func() {
		file_proto_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interceptor_proto_rawDesc), len(file_proto_interceptor_proto_rawDesc)))
	})
	return file_proto_interceptor_proto_rawDescData
}

var file_proto_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_interceptor_proto_goTypes = []any{
	(*SayHelloRequest)(nil),   // 0: interceptor.SayHelloRequest
	(*SayHelloResponse)(nil),  // 1: interceptor.SayHelloResponse
	(*ProtectedResponse)(nil), // 2: interceptor.ProtectedResponse
	(*ValidateResponse)(nil),  // 3: interceptor.ValidateResponse
	nil,                       // 4: interceptor.ValidateResponse.ClaimsEntry
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_proto_interceptor_proto_depIdxs = []int32{
	4, // 0: interceptor.ValidateResponse.claims:type_name -> interceptor.ValidateResponse.ClaimsEntry
	0, // 1: interceptor.InterceptorService.SayHello:input_type -> interceptor.SayHelloRequest
	5, // 2: interceptor.InterceptorService.LongRunning:input_type -> google.protobuf.Empty
	5, // 3: interceptor.InterceptorService.Protected:input_type -> google.protobuf.Empty
	5, // 4: interceptor.InterceptorService.Validate:input_type -> google.protobuf.Empty
	1, // 5: interceptor.InterceptorService.SayHello:output_type -> interceptor.SayHelloResponse
	5, // 6: interceptor.InterceptorService.LongRunning:output_type -> google.protobuf.Empty
	2, // 7: interceptor.InterceptorService.Protected:output_type -> interceptor.ProtectedResponse
	3, // 8: interceptor.InterceptorService.Validate:output_type -> interceptor.ValidateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_interceptor_proto_init() }
func file_proto_interceptor_proto_init() {
	if File_proto_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interceptor_proto_rawDesc), len(file_proto_interceptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interceptor_proto_goTypes,
		DependencyIndexes: file_proto_interceptor_proto_depIdxs,
		MessageInfos:      file_proto_interceptor_proto_msgTypes,
	}.Build()
	File_proto_interceptor_proto = out.File
	file_proto_interceptor_proto_goTypes = nil
	file_proto_interceptor_proto_depIdxs = nil
}
